import fs from 'fs';
import path from 'path';
import { Recorder } from '../src/recorder/Recorder';
import { Reporter } from '../src/reporter/Reporter';
import { APP_ID, APP_NAME, COMPANY_NAME, COPYRIGHT_TEXT, SHORT_NAME, TAGLINE } from '../src/config/app';

describe('OmniFlow QA product identity', () => {
  test('central identity and package metadata agree', () => {
    const pkg = JSON.parse(fs.readFileSync(path.resolve('package.json'), 'utf8'));
    expect({ APP_NAME, SHORT_NAME, COMPANY_NAME, APP_ID, TAGLINE, COPYRIGHT_TEXT }).toEqual(expect.objectContaining({
      APP_NAME: 'OmniFlow QA', SHORT_NAME: 'omniflow-qa', COMPANY_NAME: 'Infinity Lines of Code Pvt Ltd',
      APP_ID: 'com.infinitylinesofcode.omniflowqa', TAGLINE: 'Unified Web & Mobile QA Automation Studio',
    }));
    expect(pkg).toEqual(expect.objectContaining({ name: SHORT_NAME, productName: APP_NAME, author: COMPANY_NAME }));
    expect(pkg.build).toEqual(expect.objectContaining({ appId: APP_ID, productName: APP_NAME }));
    expect(pkg.build.win).toEqual(expect.objectContaining({
      icon: 'assets/omniflow-qa-icon.png',
      executableName: SHORT_NAME,
    }));
    expect(fs.existsSync(path.resolve(pkg.build.win.icon))).toBe(true);
  });

  test('uses OmniFlow branding for the Electron window and Windows taskbar identity', () => {
    const electronMain = fs.readFileSync(path.resolve('electron-main.js'), 'utf8');
    expect(electronMain).toContain("path.join(__dirname, 'assets', 'omniflow-qa-icon.png')");
    expect(electronMain).toContain('app.setAppUserModelId(APP_ID)');
    expect(electronMain).toContain('icon: APP_ICON_PATH');
    expect(electronMain).not.toContain("assets', 'icon.png'");
  });

  test('brands exported scripts and diagnostic reports', async () => {
    const recorder = new Recorder();
    const script = await recorder.exportScript('playwright');
    expect(script).toContain('Generated by OmniFlow QA');
    expect(script).toContain('Product of Infinity Lines of Code Pvt Ltd');
    const reporter = new Reporter();
    const report = { testName: 'Brand check', startTime: 1, endTime: 2, duration: 1, status: 'passed' as const,
      steps: [], screenshots: [], healingEvents: 0 };
    expect(await reporter.exportReport(report, 'html')).toContain('OmniFlow QA - Execution Diagnostics Report');
    expect(await reporter.exportReport(report, 'junit')).toContain('generator="OmniFlow QA (Infinity Lines of Code Pvt Ltd)"');
    expect(await reporter.exportReport(report, 'json')).toContain('OmniFlow QA (Infinity Lines of Code Pvt Ltd)');
  });
});
